all:
	gcc mapper.c -o mapper
	gcc reducer.c -o reducer
	gcc combiner.c -o combiner

mapper: 
	gcc mapper.c -o mapper

reducer:
	gcc reducer.c -o reducer

combiner:
	gcc combiner.c -o combiner

clean:
	rm -f mapper reducer combiner